name: RLab
favicon: null
layout_spectrum: 0.7060932
typography_spectrum: 0.02967834728769958
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#afafaf'
    - '#797979'
    - '#111111'
    - '#575757'
  brandStrength: 0.4892473
  lightness: 0.2706093
  saturation: 0.7060932
  rhythmicContrast: 0.1702509
purpose: []
