favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4318996
  brandStrength: 0.3100990601815283
  lightness: 0.08781362
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.1702509
typography_spectrum: 0.02967834728769958
layout_spectrum: 0.9301075
analytics:
  twitter: null
  google: null
  facebook: null
name: RLab
